# A staring point is the basic NIXOS configuration generated by the ISO installer.
# On an existing NIXOS install you can use the following command in your flakes basedir:
# sudo nixos-generate-config --dir ./hosts/loligo
# 
# Please make sure to change the first couple of lines in your configuration.nix:

# { config, inputs, ouputs, lib, pkgs, ... }:
#
# {
#   imports = [ # Include the results of the hardware scan.
#     ./hardware-configuration.nix
#     inputs.home-manager.nixosModules.home-manager
#   ];
#   ...
#
# Moreover please update the packages option in your user configuration and add the home-manager options:

# users.users = {
#   sqibo = {
#     isNormalUser = true;
#     initialPassword = "12345";
#     extraGroups = [ "wheel" ]; # Enable 'sudo' for the user.
#     packages = [ inputs.home-manager.packages.${pkgs.system}.default ];
#   };
# };
#
# home-manager = {
#   useUserPackages = true;
#   extraSpecialArgs = { inherit inputs outputs; };
#   users.sqibo =
#    import ../../home/sqibo/${config.networking.hostName}.nix;
# };
#
# Please also change your hostname accordingly:
#:w

# networking.hostName = "loligo"; # Define your hostname.

{ config, pkgs, ... }: {
  imports = [
    ../common
    # Include the results of the hardware scan.
    ./hardware-configuration.nix
  ];

  boot.loader.systemd-boot.enable = true; # (for UEFI systems only)

  networking = {
	hostName = "loligo";
	networkmanager.enable = true;
  };

  time.timeZone = "America/Toronto";
  i18n.defaultLocale = "en_US.UTF-8";

  users = {
	users.sqibo = {
	  isNormalUser = true;
	  description = "sqibo";
	  extraGroups = ["networkmanager" "wheel"];
	  packages = with pkgs; [];
    };
	defaultUserShell = pkgs.zsh;
  };

  nixpkgs.config.allowUnfree = true;

  programs = {
	zsh = {
	  enable = true;
	  autosuggestions.enable = true;
	  syntaxHighlighting.enable = false;
	};
  };

  environment = {
	systemPackages = with pkgs; [
	  alacritty
	  code-cursor-fhs
	  firefox
	  fuzzel
	  fzf
	  ghostty
	  git
	  neovim
	  tree
	  vim
	  waybar
	  wl-clipboard
    ];
	variables = {
	  XDG_CONFIG_HOME="$HOME/.config";
	  ZDOTDIR="$XDG_CONFIG_HOME/zsh";
	};
  };
  services = {
#	sshd.enable = true;
#	openssh = {
#	  enable = true;
#	  settings.PermitRootLogin = "no";
#	  allowSFTP = true;
#	};
  };

  nix.settings = {
	trusted-users = ["root" "sqibo"];
  };

  system.stateVersion = "25.05";
}
